config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'
  get "/home/about"=>"homes#about", as: "about"
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100,100]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @book = Book.new
    @books = Book.all
    @user=current_user

  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user=current_user
      @books=Book.all
      render :index
    end
  end



  def show
    @book=Book.find(params[:id])
    @user=@book.user
    @newbook=Book.new

  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)

  end

  def is_matching_login_user
     book=Book.find(params[:id])
    unless book.user.id==current_user.id
      redirect_to '/books'
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.all
    @user=current_user
    @book=Book.new
  end

  def show
    @user=User.find(params[:id])

    @books=@user.books
    @newbook=Book.new
  end

  def edit
    is_matching_login_user
    @user=User.find(params[:id])

  end

  def update
    is_matching_login_user
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      @users=User.all
      render :edit
    end

  end

  private

   def user_params
     params.require(:user).permit(:name, :introduction, :profile_image)

   end

   def is_matching_login_user
     user=User.find(params[:id])
    unless user.id==current_user.id
       redirect_to user_path(current_user)
    end


   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if book.errors.any? %>
  <div id="error-message">
    <h2 class="error-message-comment"><%= pluralize(book.errors.count,"error") %> prohibited this obj from being saved:</h2>
    <ul>
      <% book.errors.full_messages.each do |messege| %>
        <li><%= messege %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_newform.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user) do %>
  <div class="btn btn-block btn-outline-secondary my-5">
    <i class="fas fa-user-cog"></i>
  </div>
<% end %>


<h2>New book</h2>
<%= form_with model: book, url: '/books', method: :post do |f| %>
  <div>
    <label>Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <label>Opinion</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div>
    <%= f.submit "Create Book", class: "btn btn-success my-3" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 px-5 mx-auto">
      <h2>Editing Book</h2>
       <%= render 'error', book: @book %>

        <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>
        <div>
        <%= link_to "Show", book_path(@book.id) %>
        &#124;
        <%= link_to "Back", "/books" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 mx-0">
  <%= render 'error', book: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'newform', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1 pl-5">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to book.user do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 mx-0">
  <%= render 'error', book: @newbook %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'newform', book: @newbook, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1 pl-5">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.profile_image, size: "100x100" %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title %></td>
            <td><%= @book.body %></td>
            <% if @user==current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="d-flex flex-column col-10">
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-info mb-3" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f94369044a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class=container>
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                    <i class="fas fa-home" aria-hidden="true">Home</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users" aria-hidden="true">Users</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path,class: "nav-link text-light" do %>
                    <i class="fas fa-book-open">Books</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt">Log out</i>
                  <% end %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home">Home</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link">About</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus">Sign up</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt">Log in</i>
                  <% end %>
                </li>
              <% end %>
            </ul>

          </div>
        </div>
      </nav>
    </header>

    <main>
      <div>
        <%= flash[:notice] %>
      </div>
      <%= yield %>

    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="continer">
  <div class="row">
    <div class="col-8 px-5 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div id="error-message">
          <h2 class="error-message-comment"><%= pluralize(@user.errors.count,"error") %> prohibited this obj from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |messege| %>
              <li><%= messege %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <lanel for="inputName">Name</lanel>
          <%= f.text_field :name, autofocus: true, id: "inputName", class: "form-control" %>
        </div>
        <div class="form-group">
        <label for="inputImage">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label>Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 mx-0">
<%= render '/books/error', book: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render '/books/newform', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1 pl-5">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th><%= image_tag user.profile_image, size: "80x80" %></th>
              <th><%= user.name %></th>
              <th><%= link_to 'Show', user_path(user.id) %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 mx-0">
  <%= render '/books/error', book: @newbook %>
  <div class="row">
    <div class="col-md-3">
      <%= render '/books/newform', book: @newbook, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1 pl-5">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <th>
                <%= link_to book.user do %>
                  <%= image_tag @user.get_profile_image(80,80) %>
                <% end %>
              </th>
              <th><%= link_to book.title, book_path(book.id) %></th>
              <th><%= book.body %></th>
            </tr>
          </tbody>
        <% end %>

      </table>
    </div>
  </div>
</div>